parameters:
    clifton.cloudwatch_client_class: Aws\CloudWatch\CloudWatchClient

services:
    clifton.cloudwatch_client:
        class: '%clifton.cloudwatch_client_class%'
        arguments:
            - { region: '%aws_s3_region%', version: '2010-08-01' }

    clifton.monitoring:
        class: RMP\CloudwatchMonitoring\MonitoringHandler
        arguments:
            - '@clifton.cloudwatch_client'
            - 'clifton'
            - '%cosmos_environment%'

    clifton.monitoring_subscriber:
        class: BBC\CliftonBundle\Event\MonitoringSubscriber
        arguments: ['@logger', '@debug.stopwatch']
        tags:
            - { name: 'kernel.event_subscriber' }
            - { name: 'monolog.logger', channel: 'app_access' }

    clifton.application_time:
        class: DateTimeImmutable

    pps.mapper_factory:
        class: BBC\ProgrammesPagesService\Mapper\ProgrammesDbToDomain\MapperFactory
        public: false

    pps.service_factory:
        class: BBC\ProgrammesPagesService\Service\ServiceFactory
        arguments:
            - '@doctrine.orm.default_entity_manager'
            - '@pps.mapper_factory'

    pps.broadcasts_service:
        class: BBC\ProgrammesPagesService\Service\BroadcastsService
        factory: [ '@pps.service_factory', 'getBroadcastsService']

    pps.categories_service:
        class: BBC\ProgrammesPagesService\Service\CategoriesService
        factory: [ '@pps.service_factory', 'getCategoriesService']

    pps.collapsed_broadcasts_service:
        class: BBC\ProgrammesPagesService\Service\CollapsedBroadcastsService
        factory: [ '@pps.service_factory', 'getCollapsedBroadcastsService']

    pps.contributions_service:
        class: BBC\ProgrammesPagesService\Service\ContributionsService
        factory: [ '@pps.service_factory', 'getContributionsService']

    pps.contributors_service:
        class: BBC\ProgrammesPagesService\Service\ContributorsService
        factory: [ '@pps.service_factory', 'getContributorsService']

    pps.networks_service:
        class: BBC\ProgrammesPagesService\Service\NetworksService
        factory: [ '@pps.service_factory', 'getNetworksService']

    pps.programmes_service:
        class: BBC\ProgrammesPagesService\Service\ProgrammesService
        factory: [ '@pps.service_factory', 'getProgrammesService']

    pps.related_links_service:
        class: BBC\ProgrammesPagesService\Service\RelatedLinksService
        factory: [ '@pps.service_factory', 'getRelatedLinksService']

    pps.segments_service:
        class: BBC\ProgrammesPagesService\Service\SegmentsService
        factory: [ '@pps.service_factory', 'getSegmentsService']

    pps.segment_events_service:
        class: BBC\ProgrammesPagesService\Service\SegmentEventsService
        factory: [ '@pps.service_factory', 'getSegmentEventsService']

    pps.versions_service:
        class: BBC\ProgrammesPagesService\Service\VersionsService
        factory: [ '@pps.service_factory', 'getVersionsService']
